# PostgreSQL Northwind Database - Polar and SQL Learning

Query and explore the North database using Polars and SQL.

In [2]:
import polars as pl

In [3]:
uri_north = "postgresql://neondb_owner:npg_X9yglTDSNqI7@ep-fancy-morning-ayjb5nrr-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
query = "SELECT * FROM orders"

read_north = pl.read_database_uri(query=query, uri=uri_north)
read_north

shape: (830, 14)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ order_id ┆ customer_ ┆ employee_ ┆ order_dat ┆ … ┆ ship_city ┆ ship_regi ┆ ship_post ┆ ship_coun │
│ ---      ┆ id        ┆ id        ┆ e         ┆   ┆ ---       ┆ on        ┆ al_code   ┆ try       │
│ i16      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│          ┆ str       ┆ i16       ┆ date      ┆   ┆           ┆ str       ┆ str       ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10248    ┆ VINET     ┆ 5         ┆ 1996-07-0 ┆ … ┆ Reims     ┆ null      ┆ 51100     ┆ France    │
│          ┆           ┆           ┆ 4         ┆   ┆           ┆           ┆           ┆           │
│ 10249    ┆ TOMSP     ┆ 6         ┆ 1996-07-0 ┆ … ┆ Münster   ┆ null      ┆ 44087     ┆ Germany   │
│          ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│ 10250    ┆ HANAR     ┆ 4         ┆ 1996-07-0 ┆ … ┆ Rio de    ┆ RJ        ┆ 05454-876 ┆ Brazil    │
│          ┆           ┆           ┆ 8         ┆   ┆ Janeiro   ┆           ┆           ┆           │
│ 10251    ┆ VICTE     ┆ 3         ┆ 1996-07-0 ┆ … ┆ Lyon      ┆ null      ┆ 69004     ┆ France    │
│          ┆           ┆           ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│ 10252    ┆ SUPRD     ┆ 4         ┆ 1996-07-0 ┆ … ┆ Charleroi ┆ null      ┆ B-6000    ┆ Belgium   │
│          ┆           ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 11073    ┆ PERIC     ┆ 2         ┆ 1998-05-0 ┆ … ┆ México    ┆ null      ┆ 05033     ┆ Mexico    │
│          ┆           ┆           ┆ 5         ┆   ┆ D.F.      ┆           ┆           ┆           │
│ 11074    ┆ SIMOB     ┆ 7         ┆ 1998-05-0 ┆ … ┆ Kobenhavn ┆ null      ┆ 1734      ┆ Denmark   │
│          ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆           │
│ 11075    ┆ RICSU     ┆ 8         ┆ 1998-05-0 ┆ … ┆ Genève    ┆ null      ┆ 1204      ┆ Switzerla │
│          ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆ nd        │
│ 11076    ┆ BONAP     ┆ 4         ┆ 1998-05-0 ┆ … ┆ Marseille ┆ null      ┆ 13008     ┆ France    │
│          ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆           │
│ 11077    ┆ RATTC     ┆ 1         ┆ 1998-05-0 ┆ … ┆ Albuquerq ┆ NM        ┆ 87110     ┆ USA       │
│          ┆           ┆           ┆ 6         ┆   ┆ ue        ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
query="select * from products"
read_north

shape: (830, 14)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ order_id ┆ customer_ ┆ employee_ ┆ order_dat ┆ … ┆ ship_city ┆ ship_regi ┆ ship_post ┆ ship_coun │
│ ---      ┆ id        ┆ id        ┆ e         ┆   ┆ ---       ┆ on        ┆ al_code   ┆ try       │
│ i16      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│          ┆ str       ┆ i16       ┆ date      ┆   ┆           ┆ str       ┆ str       ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10248    ┆ VINET     ┆ 5         ┆ 1996-07-0 ┆ … ┆ Reims     ┆ null      ┆ 51100     ┆ France    │
│          ┆           ┆           ┆ 4         ┆   ┆           ┆           ┆           ┆           │
│ 10249    ┆ TOMSP     ┆ 6         ┆ 1996-07-0 ┆ … ┆ Münster   ┆ null      ┆ 44087     ┆ Germany   │
│          ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│ 10250    ┆ HANAR     ┆ 4         ┆ 1996-07-0 ┆ … ┆ Rio de    ┆ RJ        ┆ 05454-876 ┆ Brazil    │
│          ┆           ┆           ┆ 8         ┆   ┆ Janeiro   ┆           ┆           ┆           │
│ 10251    ┆ VICTE     ┆ 3         ┆ 1996-07-0 ┆ … ┆ Lyon      ┆ null      ┆ 69004     ┆ France    │
│          ┆           ┆           ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│ 10252    ┆ SUPRD     ┆ 4         ┆ 1996-07-0 ┆ … ┆ Charleroi ┆ null      ┆ B-6000    ┆ Belgium   │
│          ┆           ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 11073    ┆ PERIC     ┆ 2         ┆ 1998-05-0 ┆ … ┆ México    ┆ null      ┆ 05033     ┆ Mexico    │
│          ┆           ┆           ┆ 5         ┆   ┆ D.F.      ┆           ┆           ┆           │
│ 11074    ┆ SIMOB     ┆ 7         ┆ 1998-05-0 ┆ … ┆ Kobenhavn ┆ null      ┆ 1734      ┆ Denmark   │
│          ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆           │
│ 11075    ┆ RICSU     ┆ 8         ┆ 1998-05-0 ┆ … ┆ Genève    ┆ null      ┆ 1204      ┆ Switzerla │
│          ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆ nd        │
│ 11076    ┆ BONAP     ┆ 4         ┆ 1998-05-0 ┆ … ┆ Marseille ┆ null      ┆ 13008     ┆ France    │
│          ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆           │
│ 11077    ┆ RATTC     ┆ 1         ┆ 1998-05-0 ┆ … ┆ Albuquerq ┆ NM        ┆ 87110     ┆ USA       │
│          ┆           ┆           ┆ 6         ┆   ┆ ue        ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
q1 = (
    read_north
    .with_columns(pl.col("ship_name").str.to_uppercase())
)
q1

shape: (830, 14)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ order_id ┆ customer_ ┆ employee_ ┆ order_dat ┆ … ┆ ship_city ┆ ship_regi ┆ ship_post ┆ ship_coun │
│ ---      ┆ id        ┆ id        ┆ e         ┆   ┆ ---       ┆ on        ┆ al_code   ┆ try       │
│ i16      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│          ┆ str       ┆ i16       ┆ date      ┆   ┆           ┆ str       ┆ str       ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10248    ┆ VINET     ┆ 5         ┆ 1996-07-0 ┆ … ┆ Reims     ┆ null      ┆ 51100     ┆ France    │
│          ┆           ┆           ┆ 4         ┆   ┆           ┆           ┆           ┆           │
│ 10249    ┆ TOMSP     ┆ 6         ┆ 1996-07-0 ┆ … ┆ Münster   ┆ null      ┆ 44087     ┆ Germany   │
│          ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│ 10250    ┆ HANAR     ┆ 4         ┆ 1996-07-0 ┆ … ┆ Rio de    ┆ RJ        ┆ 05454-876 ┆ Brazil    │
│          ┆           ┆           ┆ 8         ┆   ┆ Janeiro   ┆           ┆           ┆           │
│ 10251    ┆ VICTE     ┆ 3         ┆ 1996-07-0 ┆ … ┆ Lyon      ┆ null      ┆ 69004     ┆ France    │
│          ┆           ┆           ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│ 10252    ┆ SUPRD     ┆ 4         ┆ 1996-07-0 ┆ … ┆ Charleroi ┆ null      ┆ B-6000    ┆ Belgium   │
│          ┆           ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 11073    ┆ PERIC     ┆ 2         ┆ 1998-05-0 ┆ … ┆ México    ┆ null      ┆ 05033     ┆ Mexico    │
│          ┆           ┆           ┆ 5         ┆   ┆ D.F.      ┆           ┆           ┆           │
│ 11074    ┆ SIMOB     ┆ 7         ┆ 1998-05-0 ┆ … ┆ Kobenhavn ┆ null      ┆ 1734      ┆ Denmark   │
│          ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆           │
│ 11075    ┆ RICSU     ┆ 8         ┆ 1998-05-0 ┆ … ┆ Genève    ┆ null      ┆ 1204      ┆ Switzerla │
│          ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆ nd        │
│ 11076    ┆ BONAP     ┆ 4         ┆ 1998-05-0 ┆ … ┆ Marseille ┆ null      ┆ 13008     ┆ France    │
│          ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆           │
│ 11077    ┆ RATTC     ┆ 1         ┆ 1998-05-0 ┆ … ┆ Albuquerq ┆ NM        ┆ 87110     ┆ USA       │
│          ┆           ┆           ┆ 6         ┆   ┆ ue        ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [6]:
lf_analytics = (
    pl.read_database_uri(query="SELECT * FROM order_details", uri="postgresql://neondb_owner:npg_X9yglTDSNqI7@ep-fancy-morning-ayjb5nrr-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require")
    .lazy()  
    .filter(pl.col("discount") > 0.1)
    .group_by("product_id")
    .agg(pl.col("quantity").sum())
)

# Execute the final optimized plan
df_result = lf_analytics.collect()
df_result

shape: (74, 2)
┌────────────┬──────────┐
│ product_id ┆ quantity │
│ ---        ┆ ---      │
│ i16        ┆ i64      │
╞════════════╪══════════╡
│ 49         ┆ 45       │
│ 52         ┆ 96       │
│ 31         ┆ 427      │
│ 77         ┆ 117      │
│ 62         ┆ 219      │
│ …          ┆ …        │
│ 14         ┆ 123      │
│ 25         ┆ 90       │
│ 24         ┆ 239      │
│ 43         ┆ 165      │
│ 56         ┆ 289      │
└────────────┴──────────┘

In [7]:
df_large_orders = pl.read_database_uri(
    query="SELECT * FROM orders",
    uri=uri_north,
)
# df_large_orders = df_large_orders.filter(pl.col("freight") > 100)
df_large_orders

shape: (830, 14)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ order_id ┆ customer_ ┆ employee_ ┆ order_dat ┆ … ┆ ship_city ┆ ship_regi ┆ ship_post ┆ ship_coun │
│ ---      ┆ id        ┆ id        ┆ e         ┆   ┆ ---       ┆ on        ┆ al_code   ┆ try       │
│ i16      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│          ┆ str       ┆ i16       ┆ date      ┆   ┆           ┆ str       ┆ str       ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10248    ┆ VINET     ┆ 5         ┆ 1996-07-0 ┆ … ┆ Reims     ┆ null      ┆ 51100     ┆ France    │
│          ┆           ┆           ┆ 4         ┆   ┆           ┆           ┆           ┆           │
│ 10249    ┆ TOMSP     ┆ 6         ┆ 1996-07-0 ┆ … ┆ Münster   ┆ null      ┆ 44087     ┆ Germany   │
│          ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│ 10250    ┆ HANAR     ┆ 4         ┆ 1996-07-0 ┆ … ┆ Rio de    ┆ RJ        ┆ 05454-876 ┆ Brazil    │
│          ┆           ┆           ┆ 8         ┆   ┆ Janeiro   ┆           ┆           ┆           │
│ 10251    ┆ VICTE     ┆ 3         ┆ 1996-07-0 ┆ … ┆ Lyon      ┆ null      ┆ 69004     ┆ France    │
│          ┆           ┆           ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│ 10252    ┆ SUPRD     ┆ 4         ┆ 1996-07-0 ┆ … ┆ Charleroi ┆ null      ┆ B-6000    ┆ Belgium   │
│          ┆           ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 11073    ┆ PERIC     ┆ 2         ┆ 1998-05-0 ┆ … ┆ México    ┆ null      ┆ 05033     ┆ Mexico    │
│          ┆           ┆           ┆ 5         ┆   ┆ D.F.      ┆           ┆           ┆           │
│ 11074    ┆ SIMOB     ┆ 7         ┆ 1998-05-0 ┆ … ┆ Kobenhavn ┆ null      ┆ 1734      ┆ Denmark   │
│          ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆           │
│ 11075    ┆ RICSU     ┆ 8         ┆ 1998-05-0 ┆ … ┆ Genève    ┆ null      ┆ 1204      ┆ Switzerla │
│          ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆ nd        │
│ 11076    ┆ BONAP     ┆ 4         ┆ 1998-05-0 ┆ … ┆ Marseille ┆ null      ┆ 13008     ┆ France    │
│          ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆           │
│ 11077    ┆ RATTC     ┆ 1         ┆ 1998-05-0 ┆ … ┆ Albuquerq ┆ NM        ┆ 87110     ┆ USA       │
│          ┆           ┆           ┆ 6         ┆   ┆ ue        ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Query 1: Top 5 VIP Customers by Revenue (Including Discounts)

In [8]:
df_top_customers_revenue = pl.read_database_uri(
    query="""WITH CustomerRevenue AS (
    SELECT 
        c.customer_id,
        c.company_name,
        c.country,
        ROUND(SUM(od.unit_price * od.quantity * (1 - od.discount))::numeric, 2) AS total_spent
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    JOIN order_details od ON o.order_id = od.order_id
    GROUP BY c.customer_id, c.company_name, c.country
)
SELECT customer_id, company_name, country, total_spent
FROM CustomerRevenue
ORDER BY total_spent DESC
LIMIT 5;""",
    uri=uri_north,
)
df_top_customers_revenue

shape: (5, 4)
┌─────────────┬──────────────────────────────┬─────────┬───────────────────┐
│ customer_id ┆ company_name                 ┆ country ┆ total_spent       │
│ ---         ┆ ---                          ┆ ---     ┆ ---               │
│ str         ┆ str                          ┆ str     ┆ decimal[38,10]    │
╞═════════════╪══════════════════════════════╪═════════╪═══════════════════╡
│ QUICK       ┆ QUICK-Stop                   ┆ Germany ┆ 110277.3100000000 │
│ ERNSH       ┆ Ernst Handel                 ┆ Austria ┆ 104874.9800000000 │
│ SAVEA       ┆ Save-a-lot Markets           ┆ USA     ┆ 104361.9500000000 │
│ RATTC       ┆ Rattlesnake Canyon Grocery   ┆ USA     ┆ 51097.8000000000  │
│ HUNGO       ┆ Hungry Owl All-Night Grocers ┆ Ireland ┆ 49979.9100000000  │
└─────────────┴──────────────────────────────┴─────────┴───────────────────┘

### Query 2: Product Performance & Reorder Risk Matrix

In [9]:
df_product_performance = pl.read_database_uri(
    query="""SELECT 
    p.product_id,
    p.product_name,
    cat.category_name,
    p.units_in_stock,
    p.reorder_level,
    CASE 
        WHEN p.units_in_stock = 0 THEN 'OUT OF STOCK'
        WHEN p.units_in_stock <= p.reorder_level THEN 'REORDER NOW'
        ELSE 'OK'
    END AS stock_status
FROM products p
JOIN categories cat ON p.category_id = cat.category_id
WHERE p.discontinued = 0
ORDER BY p.units_in_stock ASC;""",
    uri=uri_north,
)
df_product_performance
# df_product_ok = df_product_performance.filter(pl.col("stock_status") > 'OK')
# df_product_ok

shape: (67, 6)
┌────────────┬────────────────────┬────────────────┬────────────────┬───────────────┬──────────────┐
│ product_id ┆ product_name       ┆ category_name  ┆ units_in_stock ┆ reorder_level ┆ stock_status │
│ ---        ┆ ---                ┆ ---            ┆ ---            ┆ ---           ┆ ---          │
│ i16        ┆ str                ┆ str            ┆ i16            ┆ i16           ┆ str          │
╞════════════╪════════════════════╪════════════════╪════════════════╪═══════════════╪══════════════╡
│ 31         ┆ Gorgonzola Telino  ┆ Dairy Products ┆ 0              ┆ 20            ┆ OUT OF STOCK │
│ 21         ┆ Sir Rodney's       ┆ Confections    ┆ 3              ┆ 5             ┆ REORDER NOW  │
│            ┆ Scones             ┆                ┆                ┆               ┆              │
│ 66         ┆ Louisiana Hot      ┆ Condiments     ┆ 4              ┆ 20            ┆ REORDER NOW  │
│            ┆ Spiced Okra        ┆                ┆                ┆               ┆              │
│ 74         ┆ Longlife Tofu      ┆ Produce        ┆ 4              ┆ 5             ┆ REORDER NOW  │
│ 45         ┆ Rogede sild        ┆ Seafood        ┆ 5              ┆ 15            ┆ REORDER NOW  │
│ …          ┆ …                  ┆ …              ┆ …              ┆ …             ┆ …            │
│ 61         ┆ Sirop d'érable     ┆ Condiments     ┆ 113            ┆ 25            ┆ OK           │
│ 55         ┆ Pâté chinois       ┆ Meat/Poultry   ┆ 115            ┆ 20            ┆ OK           │
│ 6          ┆ Grandma's          ┆ Condiments     ┆ 120            ┆ 25            ┆ OK           │
│            ┆ Boysenberry Spread ┆                ┆                ┆               ┆              │
│ 40         ┆ Boston Crab Meat   ┆ Seafood        ┆ 123            ┆ 30            ┆ OK           │
│ 75         ┆ Rhönbräu           ┆ Beverages      ┆ 125            ┆ 25            ┆ OK           │
│            ┆ Klosterbier        ┆                ┆                ┆               ┆              │
└────────────┴────────────────────┴────────────────┴────────────────┴───────────────┴──────────────┘

### Query 4: Monthly Revenue Growth & Moving Averages

In [10]:
growth_query = pl.read_database_uri(
    query="""WITH MonthlySales AS (
    SELECT 
        DATE_TRUNC('month', o.order_date)::date AS order_month,
        SUM(od.unit_price * od.quantity * (1 - od.discount)) AS monthly_revenue
    FROM orders o
    JOIN order_details od ON o.order_id = od.order_id
    GROUP BY DATE_TRUNC('month', o.order_date)
)
SELECT 
    order_month,
    ROUND(monthly_revenue::numeric, 2) AS current_month_revenue,
    ROUND(LAG(monthly_revenue, 1) OVER (ORDER BY order_month)::numeric, 2) AS prior_month_revenue,
    ROUND((
        (monthly_revenue - LAG(monthly_revenue, 1) OVER (ORDER BY order_month)) 
        / LAG(monthly_revenue, 1) OVER (ORDER BY order_month) * 100
    )::numeric, 2) AS mom_growth_pct,
    ROUND(AVG(monthly_revenue) OVER(
        ORDER BY order_month 
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    )::numeric, 2) AS rolling_3_month_avg
FROM MonthlySales
ORDER BY order_month;""",
    uri=uri_north,
)
growth_query

shape: (23, 5)
┌─────────────┬───────────────────────┬─────────────────────┬────────────────┬─────────────────────┐
│ order_month ┆ current_month_revenue ┆ prior_month_revenue ┆ mom_growth_pct ┆ rolling_3_month_avg │
│ ---         ┆ ---                   ┆ ---                 ┆ ---            ┆ ---                 │
│ date        ┆ decimal[38,10]        ┆ decimal[38,10]      ┆ decimal[38,10] ┆ decimal[38,10]      │
╞═════════════╪═══════════════════════╪═════════════════════╪════════════════╪═════════════════════╡
│ 1996-07-01  ┆ 27861.9000000000      ┆ null                ┆ null           ┆ 27861.9000000000    │
│ 1996-08-01  ┆ 25485.2800000000      ┆ 27861.9000000000    ┆ -8.5300000000  ┆ 26673.5900000000    │
│ 1996-09-01  ┆ 26381.4000000000      ┆ 25485.2800000000    ┆ 3.5200000000   ┆ 26576.1900000000    │
│ 1996-10-01  ┆ 37515.7200000000      ┆ 26381.4000000000    ┆ 42.2100000000  ┆ 29794.1300000000    │
│ 1996-11-01  ┆ 45600.0500000000      ┆ 37515.7200000000    ┆ 21.5500000000  ┆ 36499.0600000000    │
│ …           ┆ …                     ┆ …                   ┆ …              ┆ …                   │
│ 1998-01-01  ┆ 94222.1100000000      ┆ 71398.4300000000    ┆ 31.9700000000  ┆ 69718.1200000000    │
│ 1998-02-01  ┆ 99415.2900000000      ┆ 94222.1100000000    ┆ 5.5100000000   ┆ 88345.2800000000    │
│ 1998-03-01  ┆ 104854.1600000000     ┆ 99415.2900000000    ┆ 5.4700000000   ┆ 99497.1800000000    │
│ 1998-04-01  ┆ 123798.6800000000     ┆ 104854.1600000000   ┆ 18.0700000000  ┆ 109356.0400000000   │
│ 1998-05-01  ┆ 18333.6300000000      ┆ 123798.6800000000   ┆ -85.1900000000 ┆ 82328.8200000000    │
└─────────────┴───────────────────────┴─────────────────────┴────────────────┴─────────────────────┘