# PostgreSQL DVD Rental Database - SQL Learning

Query and explore the DVD Rental database using SQLAlchemy and Pandas.

In [ ]:
import polars as pl

uri_dvd = "postgresql://postgres:postgres@localhost:5432/dvdrental"
query = "SELECT * FROM actor"

read_dvd = pl.read_database_uri(query=query, uri=uri_dvd)
read_dvd

shape: (200, 4)
┌──────────┬────────────┬──────────────┬─────────────────────────┐
│ actor_id ┆ first_name ┆ last_name    ┆ last_update             │
│ ---      ┆ ---        ┆ ---          ┆ ---                     │
│ i32      ┆ str        ┆ str          ┆ datetime[μs]            │
╞══════════╪════════════╪══════════════╪═════════════════════════╡
│ 1        ┆ Penelope   ┆ Guiness      ┆ 2013-05-26 14:47:57.620 │
│ 2        ┆ Nick       ┆ Wahlberg     ┆ 2013-05-26 14:47:57.620 │
│ 3        ┆ Ed         ┆ Chase        ┆ 2013-05-26 14:47:57.620 │
│ 4        ┆ Jennifer   ┆ Davis        ┆ 2013-05-26 14:47:57.620 │
│ 5        ┆ Johnny     ┆ Lollobrigida ┆ 2013-05-26 14:47:57.620 │
│ …        ┆ …          ┆ …            ┆ …                       │
│ 196      ┆ Bela       ┆ Walken       ┆ 2013-05-26 14:47:57.620 │
│ 197      ┆ Reese      ┆ West         ┆ 2013-05-26 14:47:57.620 │
│ 198      ┆ Mary       ┆ Keitel       ┆ 2013-05-26 14:47:57.620 │
│ 199      ┆ Julia      ┆ Fawcett      ┆ 2013-05-26 14:47:57.620 │
│ 200      ┆ Thora      ┆ Temple       ┆ 2013-05-26 14:47:57.620 │
└──────────┴────────────┴──────────────┴─────────────────────────┘

In [14]:
uri_north = "postgresql://postgres:postgres@localhost:5432/northwind"
query = "SELECT * FROM orders"

read_north = pl.read_database_uri(query=query, uri=uri_north)
read_north

shape: (830, 14)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ order_id ┆ customer_ ┆ employee_ ┆ order_dat ┆ … ┆ ship_city ┆ ship_regi ┆ ship_post ┆ ship_coun │
│ ---      ┆ id        ┆ id        ┆ e         ┆   ┆ ---       ┆ on        ┆ al_code   ┆ try       │
│ i16      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│          ┆ str       ┆ i16       ┆ date      ┆   ┆           ┆ str       ┆ str       ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10248    ┆ VINET     ┆ 5         ┆ 1996-07-0 ┆ … ┆ Reims     ┆ null      ┆ 51100     ┆ France    │
│          ┆           ┆           ┆ 4         ┆   ┆           ┆           ┆           ┆           │
│ 10249    ┆ TOMSP     ┆ 6         ┆ 1996-07-0 ┆ … ┆ Münster   ┆ null      ┆ 44087     ┆ Germany   │
│          ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│ 10250    ┆ HANAR     ┆ 4         ┆ 1996-07-0 ┆ … ┆ Rio de    ┆ RJ        ┆ 05454-876 ┆ Brazil    │
│          ┆           ┆           ┆ 8         ┆   ┆ Janeiro   ┆           ┆           ┆           │
│ 10251    ┆ VICTE     ┆ 3         ┆ 1996-07-0 ┆ … ┆ Lyon      ┆ null      ┆ 69004     ┆ France    │
│          ┆           ┆           ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│ 10252    ┆ SUPRD     ┆ 4         ┆ 1996-07-0 ┆ … ┆ Charleroi ┆ null      ┆ B-6000    ┆ Belgium   │
│          ┆           ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 11073    ┆ PERIC     ┆ 2         ┆ 1998-05-0 ┆ … ┆ México    ┆ null      ┆ 05033     ┆ Mexico    │
│          ┆           ┆           ┆ 5         ┆   ┆ D.F.      ┆           ┆           ┆           │
│ 11074    ┆ SIMOB     ┆ 7         ┆ 1998-05-0 ┆ … ┆ Kobenhavn ┆ null      ┆ 1734      ┆ Denmark   │
│          ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆           │
│ 11075    ┆ RICSU     ┆ 8         ┆ 1998-05-0 ┆ … ┆ Genève    ┆ null      ┆ 1204      ┆ Switzerla │
│          ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆ nd        │
│ 11076    ┆ BONAP     ┆ 4         ┆ 1998-05-0 ┆ … ┆ Marseille ┆ null      ┆ 13008     ┆ France    │
│          ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆           │
│ 11077    ┆ RATTC     ┆ 1         ┆ 1998-05-0 ┆ … ┆ Albuquerq ┆ NM        ┆ 87110     ┆ USA       │
│          ┆           ┆           ┆ 6         ┆   ┆ ue        ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [15]:
query="select * from products"
read_north

shape: (830, 14)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ order_id ┆ customer_ ┆ employee_ ┆ order_dat ┆ … ┆ ship_city ┆ ship_regi ┆ ship_post ┆ ship_coun │
│ ---      ┆ id        ┆ id        ┆ e         ┆   ┆ ---       ┆ on        ┆ al_code   ┆ try       │
│ i16      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│          ┆ str       ┆ i16       ┆ date      ┆   ┆           ┆ str       ┆ str       ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10248    ┆ VINET     ┆ 5         ┆ 1996-07-0 ┆ … ┆ Reims     ┆ null      ┆ 51100     ┆ France    │
│          ┆           ┆           ┆ 4         ┆   ┆           ┆           ┆           ┆           │
│ 10249    ┆ TOMSP     ┆ 6         ┆ 1996-07-0 ┆ … ┆ Münster   ┆ null      ┆ 44087     ┆ Germany   │
│          ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│ 10250    ┆ HANAR     ┆ 4         ┆ 1996-07-0 ┆ … ┆ Rio de    ┆ RJ        ┆ 05454-876 ┆ Brazil    │
│          ┆           ┆           ┆ 8         ┆   ┆ Janeiro   ┆           ┆           ┆           │
│ 10251    ┆ VICTE     ┆ 3         ┆ 1996-07-0 ┆ … ┆ Lyon      ┆ null      ┆ 69004     ┆ France    │
│          ┆           ┆           ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│ 10252    ┆ SUPRD     ┆ 4         ┆ 1996-07-0 ┆ … ┆ Charleroi ┆ null      ┆ B-6000    ┆ Belgium   │
│          ┆           ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 11073    ┆ PERIC     ┆ 2         ┆ 1998-05-0 ┆ … ┆ México    ┆ null      ┆ 05033     ┆ Mexico    │
│          ┆           ┆           ┆ 5         ┆   ┆ D.F.      ┆           ┆           ┆           │
│ 11074    ┆ SIMOB     ┆ 7         ┆ 1998-05-0 ┆ … ┆ Kobenhavn ┆ null      ┆ 1734      ┆ Denmark   │
│          ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆           │
│ 11075    ┆ RICSU     ┆ 8         ┆ 1998-05-0 ┆ … ┆ Genève    ┆ null      ┆ 1204      ┆ Switzerla │
│          ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆ nd        │
│ 11076    ┆ BONAP     ┆ 4         ┆ 1998-05-0 ┆ … ┆ Marseille ┆ null      ┆ 13008     ┆ France    │
│          ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆           │
│ 11077    ┆ RATTC     ┆ 1         ┆ 1998-05-0 ┆ … ┆ Albuquerq ┆ NM        ┆ 87110     ┆ USA       │
│          ┆           ┆           ┆ 6         ┆   ┆ ue        ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘